import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';

/* Flat config, straight from eslint-config-next.
 *
 * This used to run Next's presets through `FlatCompat`, which is how
 * create-next-app scaffolded it back when those presets were eslintrc-style.
 * eslint-config-next 16 ships native flat configs and ESLint 10 dropped
 * eslintrc, so the compat layer stopped being merely unnecessary and became
 * fatal: eslint-plugin-react's `configs` object references itself, and the
 * eslintrc validator JSON.stringify's the config to format an error, which
 * threw "Converting circular structure to JSON" before it could say what the
 * actual error was. Every `npx eslint` run died on startup.
 *
 * `eslint`, `next` and `eslint-config-next` are all pinned to "latest" in
 * package.json, so this arrived on its own without anybody changing a line.
 */
export default defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  {
    rules: {
      /* Off. It guards against a problem modern JSX does not have, it was 19 of
         the 24 errors on the first run that worked, and every one was an
         apostrophe in a sentence a visitor reads. The fix it wants is `&apos;`
         scattered through the copy, which makes the source harder to read to
         solve nothing. */
      'react/no-unescaped-entities': 'off',

      /* Warn, not error. All five hits are the same shape: a value the server
         cannot know, read after mount. CustomCursor asks matchMedia whether the
         pointer is fine, RotatingPill and GalleryMedia read prefers-reduced-
         motion, Nav closes the mobile sheet when the route changes. The rule is
         right that each costs one extra render, and wrong that any of them is a
         bug; doing it "properly" means a useSyncExternalStore refactor for a
         frame nobody can see. Left visible so a genuine cascading-render case
         still shows up, but not blocking a clean exit. */
      'react-hooks/set-state-in-effect': 'warn',
    },
  },
  // A globalIgnores call replaces eslint-config-next's own defaults rather
  // than adding to them, so the first four have to be repeated here.
  //
  // The rest are untracked local folders that ESLint has no business reading.
  // Flat config does not consult .gitignore, and every one of these is already
  // in it: `.source` is generated by fumadocs, and the reference folders are
  // saved third-party web pages. Linting them accounted for 175 of the 204
  // problems on the first run that worked, 162 of those in a single minified
  // Framer bundle nobody here wrote.
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    '.source/**',
    'test-results/**',
    'playwright-report/**',
    'Website inspiration/**',
    'Examples of work/**',
    'Examples of work App/**',
    'App images/**',
  ]),
]);
