import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage } from '@/components/pebble/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy policy: Pebble',
  description:
    'Pebble has no server. Symptom data lives on your phone in a local database, never transmitted, never synced. Full privacy policy.',
  alternates: { canonical: 'https://johnnybuildstech.com/apps/pebble/privacy' },
  robots: { index: true, follow: true },
};

const EFFECTIVE = '17 May 2026';
const UPDATED = '17 May 2026';

export default function PebblePrivacy() {
  return (
    <LegalPage
      eyebrow={`effective ${EFFECTIVE} · updated ${UPDATED}`}
      title="privacy policy"
      intro="Pebble is built on a single principle: your health data stays on your phone. This policy explains exactly what that means, what does leave your device, and what doesn't. Short version below, full detail beneath."
    >
      <p>
        Pebble has no server. Your symptom logs, voice notes, photos and Brief
        PDFs live on your phone in a local database. We can&rsquo;t see them,
        because there is nowhere for them to go.
      </p>

      <h2>who we are</h2>
      <p>
        Pebble is built and operated by <strong>johnnybuildstech</strong> (a sole
        trader based in the United Kingdom). Contact:{' '}
        <a href="mailto:pebble.symptom.app@gmail.com">pebble.symptom.app@gmail.com</a>.
      </p>
      <p>
        For UK GDPR purposes, johnnybuildstech is the data controller for the
        small amount of personal data described below. There is no data
        processor for your symptom data because that data never leaves your
        device.
      </p>

      <h2>what stays on your device (almost everything)</h2>
      <p>
        The following data is stored <strong>only</strong> in Pebble&rsquo;s
        local database on your phone. It is never transmitted to us or to any
        third party:
      </p>
      <ul>
        <li>symptom logs, severity ratings, mood</li>
        <li>factor entries (sleep, stress, food, medication, cycle, weather)</li>
        <li>voice notes (audio files) and their transcripts</li>
        <li>photos you attach to entries</li>
        <li>notes, tags, and free-text journalling</li>
        <li>reminders, settings, and customisations</li>
        <li>Brief PDFs you generate for appointments</li>
        <li>correlation results and pattern analyses</li>
      </ul>
      <p>
        This data is included in your phone&rsquo;s standard backup (iCloud
        Backup on iOS, Google One backup on Android) <strong>only if</strong> you
        have enabled those backups yourself. Pebble does not control those
        backups, which are operated by Apple or Google under their respective
        privacy policies. When you uninstall Pebble, this data is deleted from
        your phone along with the app.
      </p>

      <h2>what leaves your device (and only this)</h2>
      <p>Pebble makes outbound network requests in exactly two situations:</p>

      <h3>1. Weather lookup (optional, only if enabled)</h3>
      <p>
        If you turn on the Weather factor and grant location permission, Pebble
        sends your approximate (coarse) location (accurate to roughly your
        town, not your address) to <a href="https://open-meteo.com">Open-Meteo</a>{' '}
        to fetch local barometric pressure, temperature, and humidity. These
        values can correlate with flare patterns for some people.
      </p>
      <ul>
        <li>we do <strong>not</strong> send your name, email, device ID, or any symptom data</li>
        <li>
          Open-Meteo&rsquo;s privacy policy:{' '}
          <a href="https://open-meteo.com/en/terms">open-meteo.com/en/terms</a>.
          they state they do not log personal data
        </li>
        <li>
          you can disable this at any time by turning off the Weather factor or
          revoking location permission in your phone settings
        </li>
      </ul>

      <h3>2. Purchase verification</h3>
      <p>
        If you subscribe to Pebble&rsquo;s paid tier, the App Store (Apple) or
        Play Store (Google) handles the payment. To know whether your
        subscription is active, Pebble uses{' '}
        <a href="https://www.revenuecat.com">RevenueCat</a> to verify your
        purchase receipt. RevenueCat receives:
      </p>
      <ul>
        <li>an anonymous user ID generated by Pebble (not linked to your name or email)</li>
        <li>your purchase receipt from Apple or Google</li>
        <li>basic device information (model, OS version, country)</li>
      </ul>
      <p>
        RevenueCat <strong>cannot</strong> see your symptom data, voice notes,
        photos, or anything else in the app. Their privacy policy:{' '}
        <a href="https://www.revenuecat.com/privacy">revenuecat.com/privacy</a>.
      </p>

      <h2>what Pebble does NOT do</h2>
      <p>We&rsquo;ll be specific, because vague &ldquo;we respect your privacy&rdquo; claims are how privacy policies usually mislead. Pebble:</p>
      <ul>
        <li>does <strong>not</strong> use any analytics SDK (no Google Analytics, Firebase Analytics, Amplitude, Mixpanel, PostHog)</li>
        <li>does <strong>not</strong> use any crash-reporting SDK (no Sentry, Bugsnag, Crashlytics)</li>
        <li>does <strong>not</strong> have user accounts. There is no login.</li>
        <li>does <strong>not</strong> sync your data to a cloud server. There is no server.</li>
        <li>does <strong>not</strong> sell or share your data. There is nothing to sell.</li>
        <li>does <strong>not</strong> show advertising</li>
        <li>does <strong>not</strong> contain third-party tracking SDKs of any kind</li>
        <li>does <strong>not</strong> read your contacts, photo library (beyond images you explicitly attach), or messages</li>
      </ul>

      <h2>permissions Pebble requests, and why</h2>
      <table>
        <thead>
          <tr>
            <th>permission</th>
            <th>why</th>
            <th>what happens to the data</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>microphone</td>
            <td>to record voice notes</td>
            <td>audio files saved locally on your device. Never uploaded.</td>
          </tr>
          <tr>
            <td>speech recognition</td>
            <td>to transcribe voice notes</td>
            <td>
              <strong>iOS:</strong> Apple&rsquo;s on-device speech recognition.
              Audio is not sent to Apple. <strong>Android:</strong> uses
              Google&rsquo;s speech recognition service, which transmits short
              audio clips to Google for transcription under{' '}
              <a href="https://policies.google.com/privacy">Google&rsquo;s privacy policy</a>.
              The resulting text is stored locally. If you do not want this,
              leave voice notes untranscribed.
            </td>
          </tr>
          <tr>
            <td>location (approximate)</td>
            <td>optional, only if you enable the Weather factor</td>
            <td>coarse location sent to Open-Meteo (above). Never stored by us.</td>
          </tr>
          <tr>
            <td>calendar (read-only)</td>
            <td>optional, to spot upcoming appointments and pre-warm your Brief</td>
            <td>
              read once per day from your phone&rsquo;s calendar. Appointment
              text is not stored beyond a local cache of upcoming entries. Never uploaded.
            </td>
          </tr>
          <tr>
            <td>notifications</td>
            <td>to send local reminders to log</td>
            <td>local-only. Pebble does not have a push notification server.</td>
          </tr>
        </tbody>
      </table>
      <p>
        Every permission can be revoked from your phone&rsquo;s settings at any
        time without breaking the rest of the app.
      </p>

      <h2>children</h2>
      <p>
        Pebble is not directed at children under 16. If you believe a child has
        installed Pebble and you are their parent or guardian, simply uninstall
        the app. There is no account or server-side data to delete.
      </p>

      <h2>your rights (UK / EU GDPR, CCPA)</h2>
      <p>
        Because Pebble does not collect or store your personal data on any
        server, most data-subject rights are satisfied{' '}
        <strong>directly on your device</strong>:
      </p>
      <ul>
        <li><strong>access:</strong> all your data is visible inside the app, and exportable via Brief PDF / share</li>
        <li><strong>deletion:</strong> uninstall the app, or use Settings → &ldquo;delete all data&rdquo;</li>
        <li><strong>portability:</strong> the Brief PDF + share function provides a portable copy</li>
        <li><strong>rectification:</strong> edit or delete any entry from inside the app</li>
      </ul>
      <p>
        For the small categories of data we do handle off-device (Open-Meteo
        weather lookups, RevenueCat purchase records, support emails) you may
        contact{' '}
        <a href="mailto:pebble.symptom.app@gmail.com">pebble.symptom.app@gmail.com</a>{' '}
        to request access, correction, or deletion. We will respond within 30
        days.
      </p>
      <p>
        If you believe we have mishandled your data, you have the right to
        lodge a complaint with the UK Information Commissioner&rsquo;s Office
        (<a href="https://ico.org.uk">ico.org.uk</a>).
      </p>

      <h2>the marketing website</h2>
      <p>
        This privacy policy covers the Pebble mobile app. The marketing site
        you are reading this on (<a href="https://johnnybuildstech.com">johnnybuildstech.com</a>)
        is operated by the same developer and uses:
      </p>
      <ul>
        <li>Vercel for hosting and page-view analytics (no cookies, no cross-site tracking)</li>
        <li>
          Resend to handle the waitlist signup form and contact form. If you
          submit your email, it is stored in Resend&rsquo;s audience list to
          send you one launch update. You can unsubscribe at any time using the
          link in any email we send.
        </li>
      </ul>
      <p>That&rsquo;s the full list. No Google Analytics on the Pebble pages, no Facebook Pixel, no ad networks.</p>

      <h2>changes to this policy</h2>
      <p>
        If we change this policy, we&rsquo;ll update the &ldquo;last
        updated&rdquo; date at the top. For material changes (e.g. adding a new
        third-party service), we will note it on the page for at least 30 days.
      </p>

      <h2>contact</h2>
      <p>
        Questions, concerns, data requests:{' '}
        <a href="mailto:pebble.symptom.app@gmail.com">pebble.symptom.app@gmail.com</a>.
        Postal address available on request.
      </p>

      <hr />
      <p className="muted">
        Looking for the{' '}
        <Link href="/apps/pebble/support">support page</Link> or{' '}
        <Link href="/apps/pebble">Pebble itself</Link>?
      </p>
    </LegalPage>
  );
}
